# Introduction to NumPy

NumPy is a Python library used for numerical computing.  
It helps perform fast mathematical operations on arrays.

In [1]:
import numpy as np

# Creating NumPy Array

NumPy arrays allow storing multiple values in a single variable.  
They are faster and more efficient than Python lists.

In [2]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


# Creating 2D Array

A 2D array represents data in rows and columns like a table.  
It is commonly used in data analysis and machine learning.

In [3]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


# Array Properties

NumPy provides attributes to understand the structure of an array.  
These include shape, size, number of dimensions, and data type.

In [4]:
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(5,)
5
1
int32


# Special Arrays

NumPy can create arrays filled with zeros or ones quickly.  
These arrays are useful for initializing data structures.

In [5]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


# Range Arrays

NumPy provides functions to generate numbers in a range.  
`arange()` and `linspace()` create evenly spaced values.

In [6]:
print(np.arange(1,10))
print(np.linspace(1,10,5))

[1 2 3 4 5 6 7 8 9]
[ 1.    3.25  5.5   7.75 10.  ]


# Indexing

Indexing is used to access a specific element from an array.  
Index numbers start from 0 in Python.

In [7]:
print(arr[0])
print(arr[2])

10
30


# Slicing

Slicing is used to extract a portion of the array.  
The format used is `[start:end]`.

In [8]:
print(arr[1:3])

[20 30]


# Step Slicing

Step slicing allows skipping elements while selecting data.  
The format used is `[start:end:step]`.

In [9]:
print(arr[0:5:2])

[10 30 50]


# Reshape

Reshape changes the structure of an array without changing the data.  
It converts a 1D array into rows and columns.

In [10]:
arr3 = np.array([1,2,3,4,5,6])
print(arr3.reshape(2,3))

[[1 2 3]
 [4 5 6]]


# Mathematical Operations

NumPy performs element-wise mathematical operations.  
Operations apply to every element in the array.

In [11]:
arr = np.array([10,20,30])

print(arr + 5)
print(arr * 2)

[15 25 35]
[20 40 60]


# Statistical Functions

NumPy provides functions to analyze numerical data.  
Common functions include sum, mean, maximum, and minimum.

In [12]:
arr = np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

150
30.0
50
10
